/* Deliberate breakage: T23 - the grand staff and two hands.
 * Every mutation here must make `node tools/verify.js` fail. */
const { run } = require('./harness.js');

const MUTATIONS = [
  ['slots placed by index, so the two hands stop lining up in time',
   p => p.replace('const xOfBeat = (b) => startX + 14 + b * beatW;', 'const xOfBeat = (b) => startX + 14 + b * 0;')],
  ['the lower staff shifted sideways, so the hands no longer line up',
   p => p.replace('        x: xOfBeat(beats), lineY1, lineSpacing: g.lineSpacing,',
                  "        x: xOfBeat(beats) + (clef === 'bass' ? 40 : 0), lineY1, lineSpacing: g.lineSpacing,")],
  ['every note given the same width, whatever it is worth',
   p => p.replace('      const after = beats + itemBeats(item);', '      const after = beats + 1;')],
  ['the left hand drawn on the treble staff',
   p => p.replace("  drawPart(bass, g.bassY1, 'bass');", "  drawPart(bass, g.trebleY1, 'bass');")],
  ['the left hand read in the wrong clef',
   p => p.replace("  drawPart(bass, g.bassY1, 'bass');", "  drawPart(bass, g.bassY1, 'treble');")],
  ['the second staff never drawn',
   p => p.replace('  for (const top of [g.trebleTop, g.bassTop]) {', '  for (const top of [g.trebleTop]) {')],
  ['the brace dropped, so it is two staves not one instrument',
   p => p.replace('  svg += `<path d="M 13 ${g.trebleTop} C 4 ${g.trebleTop + 18}', '  svg += ``.concat(`<!-- `, `M 13 ${g.trebleTop} C 4 ${g.trebleTop + 18}')],
  ['the time signature only on the upper staff',
   p => p.replace('    for (const y1 of [g.trebleY1, g.bassY1]) {', '    for (const y1 of [g.trebleY1]) {')],
  ['bar lines drawn through the upper staff only',
   p => p.replace('svg += `<line x1="${bx}" y1="${g.trebleTop}" x2="${bx}" y2="${g.bassY1}" stroke="${STAFF_INK}" stroke-width="2"/>`;',
                  'svg += `<line x1="${bx}" y1="${g.trebleTop}" x2="${bx}" y2="${g.trebleY1}" stroke="${STAFF_INK}" stroke-width="2"/>`;')],
  ['no bar lines at all',
   p => p.replace('    for (let b = meter.capacity; b < totalBeats - 1e-9; b += meter.capacity) {', '    for (let b = meter.capacity; b < 0; b += meter.capacity) {')],
  ['hands of different lengths pass without a word',
   p => p.replace('  if (treble.length && bass.length && Math.abs(trebleLen - bassLen) > 1e-9) {', '  if (false) {')],
  ['an empty grand staff is drawn anyway',
   p => p.replace("  if (!treble.length && !bass.length) {\n    console.error('renderGrandStaff: there is nothing on either staff.');\n    return false;\n  }", '  if (false) { return false; }')],
  ['the left hand spelled out by hand instead of from the chord table',
   p => p.replace("      { chord: 'F', dur: 'h' }, { chord: 'C', dur: 'h' },\n      { chord: 'F', dur: 'h' }, { chord: 'C', dur: 'h' },",
                  "      { chord: 'G', dur: 'h' }, { chord: 'C', dur: 'h' },\n      { chord: 'F', dur: 'h' }, { chord: 'C', dur: 'h' },")],
  ['a left-hand chord that does not exist',
   p => p.replace("{ chord: 'G7', dur: 'h' }", "{ chord: 'H7', dur: 'h' }")],
  ['the left hand made a bar shorter than the right',
   p => p.replace("      { chord: 'C', dur: 'w' },\n", '')],
  ['notes that start together no longer merge into one press',
   p => p.replace('        if (!onsets.has(at)) onsets.set(at, []);', '        const at2 = at + Math.random(); if (!onsets.has(at2)) onsets.set(at2, []);')],
  ['the merged moments come out in the wrong order',
   p => p.replace('  return [...onsets.keys()].sort((a, b) => a - b).map', '  return [...onsets.keys()].sort((a, b) => b - a).map')],
  ['a moment asks for the same key twice',
   p => p.replace('for (const key of keys) if (!onsets.get(at).includes(key)) onsets.get(at).push(key);',
                  'for (const key of keys) onsets.get(at).push(key);')],
  ['the left hand left out of the merged list',
   p => p.replace('  collect(piece.treble);\n  collect(bass);', '  collect(piece.treble);')],
  ['practising two hands falls back to a single staff',
   p => p.replace('  if (practice.parts) {', '  if (false) {')],
  ['the left hand comes in a beat behind the right',
   p => p.replace("playTone(note.freq, { at: at0 + beats * secPerBeat, hold: seconds * 0.92, voice: `${tag}-${idx}-${key}` });",
                  "playTone(note.freq, { at: at0 + (beats + (clef === 'bass' ? 1 : 0)) * secPerBeat, hold: seconds * 0.92, voice: `${tag}-${idx}-${key}` });")],
  ['only the right hand is sounded',
   p => p.replace("  schedule(bass, 'bass', 'lh');", '')],
  ['a piece that does not exist is played anyway',
   p => p.replace('  if (!piece) {\n    console.error(`playTwoHands: there is no piece called "${pieceId}".`);\n    return false;\n  }', '  if (!piece) { return true; }')],
];

const { missed } = run('T23 - the grand staff and two hands', MUTATIONS);
process.exit(missed ? 1 : 0);
