/* Deliberate breakage: T24 - playing it like an organ.
 * Every mutation here must make `node tools/verify.js` fail. */
const { run } = require('./harness.js');

const MUTATIONS = [
  ['every voice given the same waveform',
   p => p.replace('    osc.type = timbre.wave;', "    osc.type = 'triangle';")],
  ['every voice given the same envelope',
   p => p.replace('    const { attack, decay, sustain, release } = timbre;',
                  '    const { attack, decay, sustain, release } = VOICES.organ;')],
  ['two voices made identical',
   p => p.replace("  flute:   { label: 'Sáo',      wave: 'sine',     attack: 0.07,  decay: 0.10, sustain: 0.88, release: 0.22 },",
                  "  flute:   { label: 'Sáo',      wave: 'sine',     attack: 0.012, decay: 0.05, sustain: 0.92, release: 0.14 },")],
  ['a voice given a waveform the browser does not have',
   p => p.replace("  strings: { label: 'Dàn dây',  wave: 'sawtooth',", "  strings: { label: 'Dàn dây',  wave: 'noise',")],
  ['a voice that does not exist is accepted',
   p => p.replace('  if (!VOICES[name]) {\n    console.error(`setVoice: there is no voice called "${name}".`);\n    return false;\n  }', '  if (!VOICES[name]) { return true; }')],
  ['a style pattern that runs past its own bar',
   p => p.replace("    bass: [[0, 0], [2, 2]],\n    chords: [[1, 0.8], [3, 0.8]],", "    bass: [[0, 0], [5, 2]],\n    chords: [[1, 0.8], [3, 0.8]],")],
  ['a style that names a drum there is none of',
   p => p.replace("[0, 'kick'], [1, 'snare'], [2, 'kick'], [3, 'snare'],", "[0, 'kick'], [1, 'rim'], [2, 'kick'], [3, 'snare'],")],
  ['a style with nothing on the first beat',
   p => p.replace("    drums: [[0, 'kick'], [1, 'snare'], [2, 'kick'], [3, 'snare'],\n            [0, 'hat'], [0.5, 'hat'],",
                  "    drums: [[1, 'snare'], [2, 'kick'], [3, 'snare'],\n            [0.5, 'hat'],")
         .replace('    bass: [[0, 0], [2, 2]],', '    bass: [[2, 2]],')
         .replace('    chords: [[1, 0.8], [3, 0.8]],\n  },\n  bolero:', '    chords: [[1, 0.8], [3, 0.8]],\n  },\n  bolero:')],
  ['a style with no chords in it',
   p => p.replace("    bass: [[0, 0], [1.5, 2], [2.5, 0]],\n    chords: [[1, 0.8], [3, 0.8]],", "    bass: [[0, 0], [1.5, 2], [2.5, 0]],\n    chords: [],")],
  ['a style that does not exist is accepted',
   p => p.replace('  if (!STYLES[styleId]) {\n    console.error(`setStyle: there is no style called "${styleId}".`);\n    return false;\n  }', '  if (!STYLES[styleId]) { return true; }')],
  ['choosing a style no longer takes its tempo',
   p => p.replace('  setPlaybackBpm(STYLES[styleId].bpm);', '')],
  ['the accompaniment plays one fixed chord whatever is chosen',
   p => p.replace("  const notes = chordVoicing(accompaniment.chord, 0);\n  if (!notes) return false;\n  const secPerBeat = 60 / player.bpm;",
                  "  const notes = chordVoicing('C', 0);\n  if (!notes) return false;\n  const secPerBeat = 60 / player.bpm;")],
  ['the bass plays the chord in its own octave instead of below it',
   p => p.replace('    const key = lowerOctave(notes[Math.min(which, notes.length - 1)]);', '    const key = notes[Math.min(which, notes.length - 1)];')],
  ['the drums dropped from the accompaniment',
   p => p.replace('  for (const [beat, kind] of style.drums) scheduleDrum(kind, at + beat * secPerBeat);', '')],
  ['the accompaniment bypasses the limiter',
   p => p.replace('  gain.connect(masterLimiter);\n  osc.start(at);\n  osc.stop(at + spec.decay + 0.02);', '  gain.connect(ctx.destination);\n  osc.start(at);\n  osc.stop(at + spec.decay + 0.02);')],
  ['a drum that never stops',
   p => p.replace('  osc.stop(at + spec.decay + 0.02);', '')],
  ['a drum that rings on for a second',
   p => p.replace("  kick:  { wave: 'sine',   from: 140,  to: 45,   fall: 0.08, peak: 0.32, decay: 0.26 },",
                  "  kick:  { wave: 'sine',   from: 140,  to: 45,   fall: 0.08, peak: 0.32, decay: 1.2 },")],
  ['a drum that does not exist is played anyway',
   p => p.replace('  if (!spec) {\n    console.error(`scheduleDrum: there is no drum called "${kind}".`);\n    return false;\n  }', '  if (!spec) { return true; }')],
  ['the kick pitched above the hat',
   p => p.replace("  kick:  { wave: 'sine',   from: 140,", "  kick:  { wave: 'sine',   from: 14000,")],
  ['starting the accompaniment twice leaves a timer behind',
   p => p.replace('  if (accompaniment.running) return false;\n  const ctx = ensureAudio();', '  const ctx = ensureAudio();')],
  ['stopping the accompaniment leaves its timer running',
   p => p.replace('  if (accompaniment.timer !== null) clearInterval(accompaniment.timer);\n  accompaniment.timer = null;\n  accompaniment.running = false;', '  accompaniment.timer = null;\n  accompaniment.running = false;')],
  ['the accompaniment scheduler runs on after being stopped',
   p => p.replace('function accompanimentScheduler() {\n  if (!accompaniment.running) return;', 'function accompanimentScheduler() {')],
  ['the first bar is scheduled in the past',
   p => p.replace('  accompaniment.nextBarTime = ctx.currentTime + 0.1;', '  accompaniment.nextBarTime = ctx.currentTime - 1;')],
  ['a black key made to name a chord',
   p => p.replace('  if (!parsed || parsed.sharp) return null;', '  if (!parsed) return null;')],
  ['B bent into a chord it is not',
   p => p.replace("const SINGLE_FINGER_CHORDS = { c: 'C', d: 'Dm', e: 'Em', f: 'F', g: 'G', a: 'Am' };",
                  "const SINGLE_FINGER_CHORDS = { c: 'C', d: 'Dm', e: 'Em', f: 'F', g: 'G', a: 'Am', b: 'G7' };")],
  ['a chord built on the wrong key',
   p => p.replace("const SINGLE_FINGER_CHORDS = { c: 'C', d: 'Dm', e: 'Em', f: 'F', g: 'G', a: 'Am' };",
                  "const SINGLE_FINGER_CHORDS = { c: 'C', d: 'Em', e: 'Dm', f: 'F', g: 'G', a: 'Am' };")],
  ['the whole keyboard treated as the left hand',
   p => p.replace('  return Boolean(parsed) && parsed.octave < ACCOMP_SPLIT_OCTAVE;', '  return Boolean(parsed);')],
  ['single-finger chords work even with the mode switched off',
   p => p.replace('  if (!singleFingerMode || !accompaniment.running) return null;', '  if (!accompaniment.running) return null;')],
  ['single-finger chords work with the accompaniment switched off',
   p => p.replace('  if (!singleFingerMode || !accompaniment.running) return null;', '  if (!singleFingerMode) return null;')],
  ['an unmapped key silently leaves the chord as it was',
   p => p.replace('    console.error(`handleSingleFinger: "${key}" does not name one of the chords this page teaches.`);\n', '')],
  ['the single-finger chord is never wired to the keys',
   p => p.replace('  handleSingleFinger(key);\n', '')],
];

const { missed } = run('T24 - playing it like an organ', MUTATIONS);
process.exit(missed ? 1 : 0);
