/* Deliberate breakage: T25 - a staff that fits the screen.
 * Every mutation here must make `node tools/verify.js` fail. */
const { run } = require('./harness.js');

const MUTATIONS = [
  ['back to one fixed width, whatever the screen',
   p => p.replace('  const viewport = (typeof window !== \'undefined\' && window.innerWidth) || 0;\n  if (!viewport) return SCORE_WIDTH.fallback;\n  return Math.max(SCORE_WIDTH.min, Math.min(SCORE_WIDTH.max, Math.min(viewport, 1152) - SCORE_CHROME));',
                  '  return 1120;')],
  ['the staff wider than the box it sits in',
   p => p.replace('const SCORE_CHROME = 104;', 'const SCORE_CHROME = 0;')],
  ['the staff allowed to grow past the page',
   p => p.replace('max: 1000,', 'max: 4000,')],
  ['the staff allowed to shrink to phone size',
   p => p.replace('min: 480,', 'min: 120,')],
  ['every line packed with twice the notes it can show',
   p => p.replace('const slotsPerSystem = (width) => Math.max(4, Math.round((width - 130) / 46));',
                  'const slotsPerSystem = (width) => Math.max(4, Math.round((width - 130) / 23));')],
  ['a wider screen no longer holds more on a line',
   p => p.replace('const slotsPerSystem = (width) => Math.max(4, Math.round((width - 130) / 46));',
                  'const slotsPerSystem = () => 12;')],
  ['the passage never breaks, however long it is',
   p => p.replace('  if (!bars || bars.starts.length <= 1) return [{ from: 0, to: items.length - 1 }];',
                  '  return [{ from: 0, to: items.length - 1 }];')],
  ['lines broken mid-bar rather than at bar lines',
   p => p.replace('  const bars = barStartIndices(items, timeSig);\n  if (!bars || bars.starts.length <= 1) return [{ from: 0, to: items.length - 1 }];',
                  '  const bars = { starts: items.map((_, i) => i) };\n  if (!bars || bars.starts.length <= 1) return [{ from: 0, to: items.length - 1 }];')],
  ['a line started one note late, so a note is dropped at every break',
   p => p.replace('    if (!current) current = { from, to, slots };', '    if (!current) current = { from: from + 1, to, slots };')],
  ['the last line left off the end of the passage',
   p => p.replace('  if (current) systems.push(current);\n  return systems;', '  return systems;')],
  ['lines allowed to overlap one another',
   p => p.replace('      systems.push(current);\n      current = null;', '      systems.push(current);')],
  ['every line restates the time signature',
   p => p.replace('{ hideMeterNumerals: i > 0 });', '{ hideMeterNumerals: false });')],
  ['a continuation line loses its bar lines along with its numerals',
   p => p.replace('      width, height, opts.timeSig, opts.keySig, { hideMeterNumerals: i > 0 });',
                  '      width, height, i === 0 ? opts.timeSig : null, opts.keySig, {});')],
  ['the first line drawn without its meter',
   p => p.replace('{ hideMeterNumerals: i > 0 });', '{ hideMeterNumerals: true });')],
  ['hiding the numerals also stops the bars being counted',
   p => p.replace('  const showMeterNumerals = Boolean(meter) && !opts.hideMeterNumerals;',
                  '  const showMeterNumerals = Boolean(meter) && !opts.hideMeterNumerals;\n  if (opts.hideMeterNumerals) meter = null;')],
  ['every line drawn into the same element, so only the last survives',
   p => p.replace('renderScoreSVG(`${containerId}-line-${i}`,', 'renderScoreSVG(`${containerId}-line-0`,')],
  ['the lines drawn but never given elements to go in',
   p => p.replace("  container.innerHTML = systems\n    .map((_, i) => `<div id=\"${containerId}-line-${i}\" class=\"w-full flex justify-center\"></div>`)\n    .join('');", "  container.innerHTML = '';")],
  ['an empty passage is drawn anyway',
   p => p.replace("  if (!Array.isArray(items) || items.length === 0) {\n    console.error(`renderScoreSystems: there is nothing to draw in \"${containerId}\".`);\n    return false;\n  }", '  if (false) { return false; }')],
  ['the keys shrunk to phone size again',
   p => p.replace('@media (max-width: 1024px) {\n  .keyboard-wrapper { padding: 10px 10px 14px 10px; }\n}',
                  '@media (max-width: 1024px) {\n  :root { --white-key-w: 22px; --black-key-w: 14px; }\n  .keyboard-wrapper { padding: 10px 10px 14px 10px; }\n}')],
  ['the tablet rules dropped, so two octaves no longer fit',
   p => p.replace('@media (max-width: 1024px) {\n  .keyboard-wrapper { padding: 10px 10px 14px 10px; }\n}', '')],
  ['the case padding left at its full-size value',
   p => p.replace('  .keyboard-wrapper { padding: 10px 10px 14px 10px; }', '  .keyboard-wrapper { padding: 10px 16px 14px 16px; }')],
];

const { missed } = run('T25 - a staff that fits the screen', MUTATIONS);
process.exit(missed ? 1 : 0);
