/* Deliberate breakage: T8 - chords.
 * Every mutation here must make `node tools/verify.js` fail. */
const { run } = require('./harness.js');

const MUTATIONS = [
  ['a minor chord written with a major third',
   p => p.replace("Dm: { label: 'Rê thứ',     notes: ['d/3', 'f/3', 'a/3'] },", "Dm: { label: 'Rê thứ',     notes: ['d/3', 'f#/3', 'a/3'] },")],
  ['a major chord written with a minor third',
   p => p.replace("C:  { label: 'Đô trưởng',  notes: ['c/3', 'e/3', 'g/3'] },", "C:  { label: 'Đô trưởng',  notes: ['c/3', 'd#/3', 'g/3'] },")],
  ['the seventh dropped from G7',
   p => p.replace("G7: { label: 'Sol bảy',    notes: ['g/3', 'b/3', 'd/4', 'f/4'] },", "G7: { label: 'Sol bảy',    notes: ['g/3', 'b/3', 'd/4'] },")],
  ['a chord written on the wrong root',
   p => p.replace("Am: { label: 'La thứ',     notes: ['a/3', 'c/4', 'e/4'] },", "Am: { label: 'La thứ',     notes: ['e/3', 'a/3', 'c/4'] },")],
  ['inversion lowers the top note instead of raising the bottom',
   p => p.replace('const raised = raiseOctave(notes.shift());', 'const raised = raiseOctave(notes.pop());')],
  ['inversion raises the note but leaves it at the bottom',
   p => p.replace('notes.push(raised);', 'notes.unshift(raised);')],
  ['raiseOctave lowers instead of raising',
   p => p.replace('Number(key.slice(cut + 1)) + 1', 'Number(key.slice(cut + 1)) - 1')],
  ['an inversion out of range is accepted',
   p => p.replace('if (!Number.isInteger(inversion) || inversion < 0 || inversion >= chord.notes.length) {', 'if (false) {')],
  ['an unknown chord name is accepted',
   p => p.replace('  if (!chord) {\n    console.error(`chordVoicing: no chord called "${chordId}".`);\n    return null;\n  }', '  if (!chord) { return CHORDS.C; }')],
  ['a chord draws a stem per note',
   p => p.replace('    if (shape.stem) {\n      const dir = stemUp ? -1 : 1;', '    for (const _s of stack) if (shape.stem) {\n      const dir = stemUp ? -1 : 1;')],
  ['the stack is spread sideways instead of stacked',
   p => p.replace('const headX = shifted[i] ? noteX + (stemUp ? 11 : -11) : noteX;', 'const headX = noteX + i * 12;')],
  ['stem direction taken from the lowest note only',
   p => p.replace('const stemUp = (lowStep + highStep) / 2 <= 4;', 'const stemUp = lowStep <= 4;')],
  ['the stem only spans the top note',
   p => p.replace('const stemY2 = (stemUp ? yOfStep(highStep) : yOfStep(lowStep)) + dir * 26;', 'const stemY2 = yOfStep(highStep) + dir * 26;')],
  ['notes a second apart are left overlapping',
   p => p.replace('shifted.push(i > 0 && steps[i] - steps[i - 1] === 1 && !shifted[i - 1]);', 'shifted.push(false);')],
  ['every note of the stack steps aside, not just seconds',
   p => p.replace('shifted.push(i > 0 && steps[i] - steps[i - 1] === 1 && !shifted[i - 1]);', 'shifted.push(i > 0);')],
  ['ledger lines drawn once per note again',
   p => p.replace('for (let l = -2; l >= s; l -= 2) if (!ledgerSteps.includes(l)) ledgerSteps.push(l);', 'for (let l = -2; l >= s; l -= 2) ledgerSteps.push(l);')],
  ['a missing note in a stack is passed over silently',
   p => p.replace('console.error(`renderScoreSVG: no "${clef}" entry for key "${stackKey}" - skipped.`);', '')],
  ['a broken chord sounds as a block',
   p => p.replace('const spread = opts.broken ? 60 / player.bpm / 2 : 0;', 'const spread = 0;')],
  ['every chord is broken, whether asked for or not',
   p => p.replace('const spread = opts.broken ? 60 / player.bpm / 2 : 0;', 'const spread = 60 / player.bpm / 2;')],
  ['a progression plays all its chords at once',
   p => p.replace('at: ctx.currentTime + 0.05 + i * secPerBar', 'at: ctx.currentTime + 0.05')],
  ['a progression puts two chords in a bar',
   p => p.replace('const secPerBar = (60 / player.bpm) * 4;', 'const secPerBar = (60 / player.bpm) * 2;')],
  ['a progression index out of range is accepted',
   p => p.replace('  if (!progression) {\n    console.error(`playProgression: there is no progression ${index}.`);\n    return false;\n  }', '  if (!progression) { return true; }')],
  ['an inversion outside the three basic positions is accepted',
   p => p.replace('if (!Number.isInteger(inversion) || inversion < 0 || inversion > 2) {', 'if (false) {')],
];

const { missed } = run('T8 - chords', MUTATIONS);
process.exit(missed ? 1 : 0);
